import { assets } from "@/lib/assets";
import type { Agent, City, Property, Region, University } from "@/types/property";

export const activeRegions: Region[] = [
  { slug: "jalal-abad", name: "Jalal-Abad", status: "active" }
];

export const comingSoonRegions: Region[] = [
  { slug: "bishkek", name: "Bishkek", status: "coming-soon" },
  { slug: "osh", name: "Osh", status: "coming-soon" },
  { slug: "kant", name: "Kant", status: "coming-soon" },
  { slug: "karakol", name: "Karakol", status: "coming-soon" },
  { slug: "naryn", name: "Naryn", status: "coming-soon" },
  { slug: "talas", name: "Talas", status: "coming-soon" },
  { slug: "batken", name: "Batken", status: "coming-soon" }
];

export const properties: Property[] = [
  {
    id: "STN-JAB-1001",
    slug: "jaiu-riverside-studio",
    title: "JAIU Riverside Studio",
    name: "JAIU Riverside Studio",
    price: "18,000 сом",
    priceMonthly: 18000,
    location: "Lenin Street, Jalal-Abad",
    city: "Jalal-Abad",
    region: "Jalal-Abad",
    university: "Jalal-Abad International University (JAIU)",
    distance: "2 mins from JAIU",
    roommates: 0,
    roomType: "Studio",
    furnished: true,
    utilitiesIncluded: true,
    badges: ["WiFi Included", "Fully Furnished", "Bills Included"],
    amenities: ["Fast WiFi", "Study desk", "Private bathroom", "Laundry access", "Heating", "Kitchenette"],
    availabilityDate: "2026-08-01",
    image: assets.property1,
    images: [assets.property1, assets.heroSmall, assets.heroHome],
    popular: true,
    verified: true,
    genderPreference: "Mixed",
    type: "Studio",
    agent: "Aida Karimova",
    landlordPhone: "+996555011697",
    description: "A quiet verified studio for JAIU students who want a private space close to campus, food spots, and evening transport."
  },
  {
    id: "STN-JAB-1002",
    slug: "jasu-central-shared-flat",
    title: "JASU Central Shared Flat",
    name: "JASU Central Shared Flat",
    price: "13,000 сом",
    priceMonthly: 13000,
    location: "Toktogul Avenue, Jalal-Abad",
    city: "Jalal-Abad",
    region: "Jalal-Abad",
    university: "Jalal-Abad State University (JASU)",
    distance: "6 mins from JASU",
    roommates: 2,
    roomType: "Shared room",
    furnished: true,
    utilitiesIncluded: true,
    badges: ["2 Roommates", "Bills Included", "Verified Landlord"],
    amenities: ["Shared kitchen", "WiFi Included", "Balcony", "Washing machine", "Heating", "Bus nearby"],
    availabilityDate: "2026-07-15",
    image: assets.property2,
    images: [assets.property2, assets.heroSmallAlt, assets.tenantHome],
    popular: true,
    verified: true,
    genderPreference: "Mixed",
    type: "Shared Room",
    agent: "Daniel Reyes",
    landlordPhone: "+996555011697",
    description: "A bright shared flat for JASU students, with friendly roommates, a study-ready living room, and simple routes to class."
  },
  {
    id: "STN-JAB-1003",
    slug: "caimu-medical-room",
    title: "CAIMU Medical Room",
    name: "CAIMU Medical Room",
    price: "15,000 сом",
    priceMonthly: 15000,
    location: "Sputnik District, Jalal-Abad",
    city: "Jalal-Abad",
    region: "Jalal-Abad",
    university: "Central Asian International Medical University (CAIMU)",
    distance: "5 mins from CAIMU",
    roommates: 1,
    roomType: "Private room",
    furnished: true,
    utilitiesIncluded: false,
    badges: ["Private Room", "Study Desk", "Female Only"],
    amenities: ["Study desk", "Quiet hours", "Security entrance", "Heating", "Shared kitchen", "Near clinic"],
    availabilityDate: "2026-06-20",
    image: assets.property3,
    images: [assets.property3, assets.property1, assets.heroSmall],
    popular: true,
    verified: true,
    genderPreference: "Female only",
    type: "Shared Room",
    agent: "Ava Sullivan",
    landlordPhone: "+996555011697",
    description: "A calm private room for CAIMU medical students, with a study desk, reliable heating, and a verified host."
  },
  {
    id: "STN-JAB-1004",
    slug: "jaiu-campus-apartment",
    title: "JAIU Campus Apartment",
    name: "JAIU Campus Apartment",
    price: "25,000 сом",
    priceMonthly: 25000,
    location: "Kurmanbek Street, Jalal-Abad",
    city: "Jalal-Abad",
    region: "Jalal-Abad",
    university: "Jalal-Abad International University (JAIU)",
    distance: "12 mins by shuttle to JAIU",
    roommates: 3,
    roomType: "Apartment",
    furnished: true,
    utilitiesIncluded: true,
    badges: ["3 Roommates", "Virtual Tour", "WiFi Included"],
    amenities: ["Virtual tour", "Shared kitchen", "Laundry access", "Fast WiFi", "Study area", "Bills Included"],
    availabilityDate: "2026-08-10",
    image: assets.property4,
    images: [assets.property4, assets.tenantHome, assets.heroHome],
    verified: true,
    genderPreference: "Mixed",
    type: "Apartment",
    agent: "Nora Blake",
    landlordPhone: "+996555011697",
    description: "A spacious Jalal-Abad student apartment with a virtual tour, shared kitchen, laundry access, and shuttle routes."
  },
  {
    id: "STN-JAB-1005",
    slug: "jasu-budget-student-room",
    title: "JASU Budget Student Room",
    name: "JASU Budget Student Room",
    price: "11,000 сом",
    priceMonthly: 11000,
    location: "Kok-Art Microdistrict, Jalal-Abad",
    city: "Jalal-Abad",
    region: "Jalal-Abad",
    university: "Jalal-Abad State University (JASU)",
    distance: "9 mins from JASU",
    roommates: 2,
    roomType: "Shared room",
    furnished: true,
    utilitiesIncluded: true,
    badges: ["Affordable", "Bills Included", "2 Roommates"],
    amenities: ["Bills Included", "Shared kitchen", "Study desk", "Heating", "Market nearby", "WiFi Included"],
    availabilityDate: "2026-06-01",
    image: assets.property5,
    images: [assets.property5, assets.property6, assets.heroSmallAlt],
    verified: true,
    genderPreference: "Male only",
    type: "Shared Room",
    agent: "Sam Cooper",
    landlordPhone: "+996555011697",
    description: "A budget-friendly shared room for JASU students who want a simple verified place close to class and everyday food spots."
  },
  {
    id: "STN-JAB-1006",
    slug: "caimu-exchange-house",
    title: "CAIMU Exchange House",
    name: "CAIMU Exchange House",
    price: "14,000 сом",
    priceMonthly: 14000,
    location: "Central Jalal-Abad",
    city: "Jalal-Abad",
    region: "Jalal-Abad",
    university: "Central Asian International Medical University (CAIMU)",
    distance: "18 mins by shuttle to CAIMU",
    roommates: 4,
    roomType: "Private room",
    furnished: true,
    utilitiesIncluded: true,
    badges: ["Exchange Friendly", "Shared Kitchen", "WiFi Included"],
    amenities: ["Exchange friendly", "Garden", "Shared kitchen", "WiFi Included", "Shuttle route", "Flexible move-in"],
    availabilityDate: "2026-07-01",
    image: assets.property6,
    images: [assets.property6, assets.property2, assets.tenantHome],
    verified: true,
    genderPreference: "Mixed",
    type: "Shared Room",
    agent: "Aida Karimova",
    landlordPhone: "+996555011697",
    description: "A friendly Jalal-Abad house for exchange and medical students, with flexible move-in dates and verified landlord support."
  }
];

export const agents: Agent[] = [
  { slug: "aida-karimova", name: "Aida Karimova", title: "Student Housing Advisor", location: "Jalal-Abad", rating: 4.9, deals: 184 },
  { slug: "daniel-reyes", name: "Daniel Reyes", title: "International Student Host", location: "Jalal-Abad", rating: 4.8, deals: 136 },
  { slug: "ava-sullivan", name: "Ava Sullivan", title: "Verified Landlord Partner", location: "Jalal-Abad", rating: 4.9, deals: 207 }
];

export const universities: University[] = [
  { slug: "jaiu", name: "Jalal-Abad International University (JAIU)", city: "Jalal-Abad", apartmentCount: 128, averageRent: "16,500 сом", nearbyListings: 46 },
  { slug: "jasu", name: "Jalal-Abad State University (JASU)", city: "Jalal-Abad", apartmentCount: 164, averageRent: "13,000 сом", nearbyListings: 58 },
  { slug: "caimu", name: "Central Asian International Medical University (CAIMU)", city: "Jalal-Abad", apartmentCount: 96, averageRent: "15,500 сом", nearbyListings: 34 }
];

export const cities: City[] = [
  { slug: "jalal-abad", name: "Jalal-Abad", count: 388, averageRent: "14,800 сом", status: "active" },
  { slug: "bishkek", name: "Bishkek", count: 0, averageRent: "Soon", status: "coming-soon" },
  { slug: "osh", name: "Osh", count: 0, averageRent: "Soon", status: "coming-soon" },
  { slug: "kant", name: "Kant", count: 0, averageRent: "Soon", status: "coming-soon" },
  { slug: "karakol", name: "Karakol", count: 0, averageRent: "Soon", status: "coming-soon" },
  { slug: "naryn", name: "Naryn", count: 0, averageRent: "Soon", status: "coming-soon" },
  { slug: "talas", name: "Talas", count: 0, averageRent: "Soon", status: "coming-soon" },
  { slug: "batken", name: "Batken", count: 0, averageRent: "Soon", status: "coming-soon" }
];
